CREATE DATABASE IF NOT EXISTS ADAqua CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ADAqua;

CREATE TABLE IF NOT EXISTS Aquariums (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    Name VARCHAR(120) NOT NULL,
    VolumeLiters DECIMAL(8,2) NOT NULL,
    WaterType VARCHAR(80) NOT NULL,
    StartedOn DATE NOT NULL,
    Notes TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WaterMeasurements (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    AquariumId CHAR(36) NOT NULL,
    MeasuredAt DATETIME NOT NULL,
    Ammonia DECIMAL(6,3) NULL,
    Nitrites DECIMAL(6,3) NULL,
    Nitrates DECIMAL(6,3) NULL,
    Ph DECIMAL(4,2) NULL,
    Gh DECIMAL(5,2) NULL,
    Kh DECIMAL(5,2) NULL,
    TemperatureCelsius DECIMAL(5,2) NULL,
    Notes TEXT NOT NULL,
    CONSTRAINT FK_WaterMeasurements_Aquariums FOREIGN KEY (AquariumId) REFERENCES Aquariums(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AquariumPlants (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    AquariumId CHAR(36) NOT NULL,
    AddedOn DATE NOT NULL,
    CommonName VARCHAR(120) NOT NULL,
    ScientificName VARCHAR(160) NOT NULL,
    GrowthSpeed VARCHAR(30) NOT NULL,
    LightNeed VARCHAR(80) NOT NULL,
    Notes TEXT NOT NULL,
    CONSTRAINT FK_AquariumPlants_Aquariums FOREIGN KEY (AquariumId) REFERENCES Aquariums(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PopulationMembers (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    AquariumId CHAR(36) NOT NULL,
    AddedOn DATE NOT NULL,
    SpeciesName VARCHAR(160) NOT NULL,
    CommonName VARCHAR(120) NOT NULL,
    Type VARCHAR(40) NOT NULL,
    Quantity INT NOT NULL,
    Notes TEXT NOT NULL,
    CONSTRAINT FK_PopulationMembers_Aquariums FOREIGN KEY (AquariumId) REFERENCES Aquariums(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AquariumInterventions (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    AquariumId CHAR(36) NOT NULL,
    OccurredAt DATETIME NOT NULL,
    Type VARCHAR(40) NOT NULL,
    ProductName VARCHAR(160) NOT NULL,
    ProductQuantity VARCHAR(80) NOT NULL,
    WaterVolumeLiters DECIMAL(8,2) NULL,
    WaterPercentage DECIMAL(5,2) NULL,
    PopulationChangeReason VARCHAR(220) NOT NULL,
    PopulationChangeCount INT NULL,
    Notes TEXT NOT NULL,
    CONSTRAINT FK_AquariumInterventions_Aquariums FOREIGN KEY (AquariumId) REFERENCES Aquariums(Id) ON DELETE CASCADE,
    INDEX IX_AquariumInterventions_AquariumId_OccurredAt (AquariumId, OccurredAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PlantReferences (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    Environment VARCHAR(40) NOT NULL,
    CommonName VARCHAR(160) NOT NULL,
    CommonNameFr VARCHAR(160) NULL,
    CommonNameEn VARCHAR(160) NULL,
    CommonNameDe VARCHAR(160) NULL,
    ScientificName VARCHAR(180) NOT NULL,
    PhMin DECIMAL(5,2) NULL,
    PhMax DECIMAL(5,2) NULL,
    GhMin DECIMAL(6,2) NULL,
    GhMax DECIMAL(6,2) NULL,
    KhMin DECIMAL(6,2) NULL,
    KhMax DECIMAL(6,2) NULL,
    TemperatureMin DECIMAL(5,2) NULL,
    TemperatureMax DECIMAL(5,2) NULL,
    AmmoniaMin DECIMAL(7,3) NULL,
    AmmoniaMax DECIMAL(7,3) NULL,
    NitritesMin DECIMAL(7,3) NULL,
    NitritesMax DECIMAL(7,3) NULL,
    NitratesMin DECIMAL(7,3) NULL,
    NitratesMax DECIMAL(7,3) NULL,
    VolumeMinLiters INT NULL,
    LightNeed VARCHAR(120) NOT NULL,
    Co2Need VARCHAR(120) NOT NULL,
    FertilizationNeed VARCHAR(120) NOT NULL,
    GrowthSpeed VARCHAR(80) NOT NULL,
    RecommendedPlacement VARCHAR(120) NOT NULL,
    Behavior VARCHAR(180) NOT NULL,
    Compatibility VARCHAR(220) NOT NULL,
    SourceUrl VARCHAR(512) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PlantReferenceImportCandidates (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    RunId CHAR(36) NOT NULL,
    CollectedAt DATETIME NOT NULL,
    SourceName VARCHAR(80) NOT NULL,
    SourceUrl VARCHAR(512) NOT NULL,
    Environment VARCHAR(40) NOT NULL,
    CommonName VARCHAR(160) NULL,
    CommonNameFr VARCHAR(160) NULL,
    CommonNameEn VARCHAR(160) NULL,
    CommonNameDe VARCHAR(160) NULL,
    ScientificName VARCHAR(180) NULL,
    PhMin DECIMAL(5,2) NULL,
    PhMax DECIMAL(5,2) NULL,
    GhMin DECIMAL(6,2) NULL,
    GhMax DECIMAL(6,2) NULL,
    KhMin DECIMAL(6,2) NULL,
    KhMax DECIMAL(6,2) NULL,
    TemperatureMin DECIMAL(5,2) NULL,
    TemperatureMax DECIMAL(5,2) NULL,
    AmmoniaMin DECIMAL(7,3) NULL,
    AmmoniaMax DECIMAL(7,3) NULL,
    NitritesMin DECIMAL(7,3) NULL,
    NitritesMax DECIMAL(7,3) NULL,
    NitratesMin DECIMAL(7,3) NULL,
    NitratesMax DECIMAL(7,3) NULL,
    VolumeMinLiters INT NULL,
    LightNeed VARCHAR(120) NULL,
    Co2Need VARCHAR(120) NULL,
    FertilizationNeed VARCHAR(120) NULL,
    GrowthSpeed VARCHAR(80) NULL,
    RecommendedPlacement VARCHAR(120) NULL,
    Behavior VARCHAR(180) NULL,
    Compatibility VARCHAR(220) NULL,
    EssentialParameterCount INT NOT NULL,
    CandidateStatus VARCHAR(60) NOT NULL,
    RejectionReason VARCHAR(220) NOT NULL,
    INDEX IX_PlantReferenceImportCandidates_RunId (RunId),
    INDEX IX_PlantReferenceImportCandidates_SourceName (SourceName),
    INDEX IX_PlantReferenceImportCandidates_ScientificName (ScientificName),
    INDEX IX_PlantReferenceImportCandidates_Status (CandidateStatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AnimalReferences (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    Environment VARCHAR(40) NOT NULL,
    CommonName VARCHAR(160) NOT NULL,
    CommonNameFr VARCHAR(160) NULL,
    CommonNameEn VARCHAR(160) NULL,
    CommonNameDe VARCHAR(160) NULL,
    ScientificName VARCHAR(180) NOT NULL,
    PhMin DECIMAL(5,2) NULL,
    PhMax DECIMAL(5,2) NULL,
    GhMin DECIMAL(6,2) NULL,
    GhMax DECIMAL(6,2) NULL,
    KhMin DECIMAL(6,2) NULL,
    KhMax DECIMAL(6,2) NULL,
    TemperatureMin DECIMAL(5,2) NULL,
    TemperatureMax DECIMAL(5,2) NULL,
    AmmoniaMin DECIMAL(7,3) NULL,
    AmmoniaMax DECIMAL(7,3) NULL,
    NitritesMin DECIMAL(7,3) NULL,
    NitritesMax DECIMAL(7,3) NULL,
    NitratesMin DECIMAL(7,3) NULL,
    NitratesMax DECIMAL(7,3) NULL,
    VolumeMinLiters INT NULL,
    Behavior VARCHAR(180) NOT NULL,
    Compatibility VARCHAR(220) NOT NULL,
    SourceUrl VARCHAR(512) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AnimalReferenceImportCandidates (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    RunId CHAR(36) NOT NULL,
    CollectedAt DATETIME NOT NULL,
    SourceName VARCHAR(80) NOT NULL,
    SourceUrl VARCHAR(512) NOT NULL,
    Environment VARCHAR(40) NOT NULL,
    CommonName VARCHAR(160) NULL,
    CommonNameFr VARCHAR(160) NULL,
    CommonNameEn VARCHAR(160) NULL,
    CommonNameDe VARCHAR(160) NULL,
    ScientificName VARCHAR(180) NULL,
    PhMin DECIMAL(5,2) NULL,
    PhMax DECIMAL(5,2) NULL,
    GhMin DECIMAL(6,2) NULL,
    GhMax DECIMAL(6,2) NULL,
    KhMin DECIMAL(6,2) NULL,
    KhMax DECIMAL(6,2) NULL,
    TemperatureMin DECIMAL(5,2) NULL,
    TemperatureMax DECIMAL(5,2) NULL,
    AmmoniaMin DECIMAL(7,3) NULL,
    AmmoniaMax DECIMAL(7,3) NULL,
    NitritesMin DECIMAL(7,3) NULL,
    NitritesMax DECIMAL(7,3) NULL,
    NitratesMin DECIMAL(7,3) NULL,
    NitratesMax DECIMAL(7,3) NULL,
    VolumeMinLiters INT NULL,
    EssentialParameterCount INT NOT NULL,
    CandidateStatus VARCHAR(60) NOT NULL,
    RejectionReason VARCHAR(220) NOT NULL,
    INDEX IX_AnimalReferenceImportCandidates_RunId (RunId),
    INDEX IX_AnimalReferenceImportCandidates_SourceName (SourceName),
    INDEX IX_AnimalReferenceImportCandidates_ScientificName (ScientificName),
    INDEX IX_AnimalReferenceImportCandidates_Status (CandidateStatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
